name: octo_image
description: A multifunctional Flutter image widget. Supports placeholders, error widgets and image transformers with fading.
version: 1.0.2
homepage: https://github.com/Baseflow/octo_image
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blurhash: ">=0.6.0 <0.8.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
